---
- name: Set Up mongod.conf
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'

- name: Mount Disk by LABEL
  mount:
    path: "{{hostvars[inventory_hostname]['mongo_db_mount_dir']}}"
    src: LABEL={{hostvars[inventory_hostname]['diskLabel']}}
    fstype: xfs
    state: mounted

- name: check if log folder already exists
  stat: path={hostvars[inventory_hostname]['mongo_log_path_dir']}}
  register: log_folder

- name: re-create log folder
  file: path={hostvars[inventory_hostname]['mongo_log_path_dir']}} state=directory
  when: log_folder.stat.isdir is defined and log_folder.stat.isdir == false

- name: Change permission
  file: dest={{hostvars[inventory_hostname]['mongo_db_path']}} owner=mongod group=mongod mode=u=rwX,g=rX,o=rX recurse=yes

- name: Change permission
  file: dest={{hostvars[inventory_hostname]['mongo_log_path_dir']}} owner=mongod group=mongod mode=u=rwX,g=rX,o=rX recurse=yes

