---
- name: Copy repo file to repos
  copy: 
   dest: /etc/yum.repos.d/mongodb.repo 
   src: files/mongodb.repo 

- name: Install MongoDB from repo
  yum:
   name: mongodb-org
   state: present

- name: MongoDB - stop server
  service: name=mongod state=stopped
  when: mongo_bin.stat.exists == False

- name: Check if ssl folder already exists
  stat: path=/etc/ssl
  register: ssl_folder

- name: Re-create ssl folder
  file: path=/etc/ssl state=directory
  when: (ssl_folder.stat.isdir == False) or ({{ force|default(False) }} == True)

- name: Create self-signed SSL cert
  command: openssl req -newkey rsa:2048 -new -x509 -days 365 -nodes -subj "/C=FR/ST=PACA/L=SophiaAntipolis/O=YourOrga/CN=contact@yourorga.com" -out /etc/ssl/mongodb-cert.crt -keyout /etc/ssl/mongodb-cert.key

- name: Compile self-signed SSL cert in PEM file
  shell: cat /etc/ssl/mongodb-cert.key /etc/ssl/mongodb-cert.crt > /etc/ssl/mongodb.pem

#- name: Upload relevant key for mongo authentication

- name: Set Up mongod.conf
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'

- name: Change system limits in sysctl.conf

- name: Mount Disk by LABEL
   path: {{ mongo_db_path }}
   src: LABEL=mongodbextdisk
   fstype: ext4
   opts:
   state: mounted

- name: Enable and start Mongod Service
  service: 
   name: mongod
   state: restarted
   enabled: yes
